# Generated by Django 5.0.6 on 2024-06-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_service', '0003_issue_message_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue_message',
            options={'ordering': ('-created_at',)},
        ),
    ]
