# Generated by Django 5.0.6 on 2024-06-23 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0010_alter_profile_avatar_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
