# Generated by Django 5.0.6 on 2024-07-20 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0011_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
