# Generated by Django 5.0.6 on 2024-06-14 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_region_country_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterField(
            model_name='decade',
            name='label',
            field=models.CharField(choices=[('1920s', '1920s'), ('1930s', '1930s'), ('1940s', '1940s'), ('1950s', '1950s'), ('1960s', '1960s'), ('1970s', '1970s'), ('1980s', '1980s'), ('1990s', '1990s'), ('2000s', '2000s')], max_length=5),
        ),
        migrations.AlterField(
            model_name='director',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directors', to='movie.country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
