# Generated by Django 5.0.6 on 2024-06-14 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_country_options_alter_decade_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decade',
            name='label',
        ),
        migrations.AlterField(
            model_name='movie',
            name='decade',
            field=models.CharField(choices=[('1920s', '1920s'), ('1930s', '1930s'), ('1940s', '1940s'), ('1950s', '1950s'), ('1960s', '1960s'), ('1970s', '1970s'), ('1980s', '1980s'), ('1990s', '1990s'), ('2000s', '2000s')], max_length=5, null=True),
        ),
    ]
