# Generated by Django 5.0.6 on 2024-06-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_genre_movie_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='keywords',
            field=models.ManyToManyField(to='movie.keyword'),
        ),
    ]
