# Generated by Django 5.0.6 on 2024-06-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_keyword_movie_keywords'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'ordering': ('last_name',)},
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
