# Generated by Django 5.0.6 on 2024-06-18 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_vote'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
