# Generated by Django 5.0.6 on 2024-06-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0011_delete_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='youtube_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
