# Generated by Django 5.0.6 on 2024-06-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0012_movie_youtube_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('label',)},
        ),
    ]
